### ISSUE TITLE
Some problematic display with related to geojson-vt

### ISSUE THREAD

**Issue by ismail-codar** [GlobeletJS/vector-map#3]
Maybe you are aware. https://globeletjs.github.io/tile-setter/examples/geojson/index.html There are some display problems on some zoom levels. 
For example:
![image](https://user-images.githubusercontent.com/282104/95688085-3863b280-0c10-11eb-9bd9-6c2b7a7fcb30.png)

**Comment by jjhembd** [comment]
Hi @ismail-codar , sorry for the (extremely) delayed response. 
This issue has been fixed by adjusting the default `tolerance` parameter that we set in [geojson-mvt](https://github.com/mapbox/geojson-vt). We call geojson-mvt from [this code in tile-retriever](https://github.com/GlobeletJS/tile-retriever/blob/main/src/geojson.js).

The example you linked has been changed to a more general GeoJSON sampler file. But if I load the same "US states" file that you displayed, the result seems OK now.

![image](https://user-images.githubusercontent.com/41167620/155389387-432a3a0d-3821-4e4f-ac68-d68082bb0997.png)

Thanks for your feedback! Let us know if you find any other issues.
